#!/bin/sh

DIR=`pwd`
# VCS_REF=`git rev-parse --short HEAD`
VERSION=`date +%-Y.%-m%d.%-H%M`

# npm install -g web-ext

TEMP_DIR=${DIR}/temp/firefox
cd ${DIR}
mkdir -p ${TEMP_DIR}
cp -r icons ${TEMP_DIR}/
cp -r _locales ${TEMP_DIR}/
cp *.js ${TEMP_DIR}/
cp LICENSE ${TEMP_DIR}/
cp README.md ${TEMP_DIR}/
cp manifest.json.firefox ${TEMP_DIR}/manifest.json
sed -i -e "s|\"version\": \"0.0.1\"|\"version\": \"${VERSION}\"|g" ${TEMP_DIR}/manifest.json
cd ${TEMP_DIR}
web-ext build --ignore-files temp --overwrite-dest
web-ext lint

TEMP_DIR=${DIR}/temp/chrome
cd ${DIR}
mkdir -p ${TEMP_DIR}
cp -r icons ${TEMP_DIR}/
cp -r _locales ${TEMP_DIR}/
cp *.js ${TEMP_DIR}/
cp LICENSE ${TEMP_DIR}/
cp README.md ${TEMP_DIR}/
cp manifest.json.chrome ${TEMP_DIR}/manifest.json
sed -i -e "s|\"version\": \"0.0.1\"|\"version\": \"${VERSION}\"|g" ${TEMP_DIR}/manifest.json
cd ${TEMP_DIR}
web-ext build --ignore-files temp --overwrite-dest
web-ext lint

